# Generated by Django 4.2.6 on 2023-10-31 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Text",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("action", models.CharField(max_length=100)),
            ],
        ),
    ]
